### ISSUE TITLE
'type' is not subscriptable

### ISSUE THREAD

**Issue by nyashi** [ombe1229/holodex#37]
![Screenshot_20220727-024246](https://user-images.githubusercontent.com/93364732/181170286-ded4dd2e-24be-4744-90ea-d3d2744b2dbd.png)
In the class HolodexHttpClient
Are
exc_type: Optional[type[BaseException]]

Instead of
exc_type: Optional[type(BaseException)]
In __aenter__

**Comment by ombe1229** [comment]
I will fix it in [0.11.11](https://github.com/ombe1229/holodex/releases/tag/0.11.11), Thanks for your contribution.
